# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 456abdcaefd2adcfd55ca96eca640ea3a3509f702538872247a1c9dcab66b42de40103dc4f78cae21b87979759d354eb0f55d63a103c43852741b7562f363425

test:
  secret_key_base: 551c2b4068c0f2c064597a1745194ac75418f09cbc61c31ac0268c01c3c07d2e3b985c6d565f28a2153dd1d4d85abc8584ef1fbcc9d29c1164999c634b99b1b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
